#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BTL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLbanhoaqua3")]
	public partial class HoaquaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCalamviec(Calamviec instance);
    partial void UpdateCalamviec(Calamviec instance);
    partial void DeleteCalamviec(Calamviec instance);
    partial void InsertChitietcalam(Chitietcalam instance);
    partial void UpdateChitietcalam(Chitietcalam instance);
    partial void DeleteChitietcalam(Chitietcalam instance);
    partial void InsertHoadonban(Hoadonban instance);
    partial void UpdateHoadonban(Hoadonban instance);
    partial void DeleteHoadonban(Hoadonban instance);
    partial void InsertHoaDonNhap(HoaDonNhap instance);
    partial void UpdateHoaDonNhap(HoaDonNhap instance);
    partial void DeleteHoaDonNhap(HoaDonNhap instance);
    partial void InsertKhachhang(Khachhang instance);
    partial void UpdateKhachhang(Khachhang instance);
    partial void DeleteKhachhang(Khachhang instance);
    partial void InsertLoaihoaqua(Loaihoaqua instance);
    partial void UpdateLoaihoaqua(Loaihoaqua instance);
    partial void DeleteLoaihoaqua(Loaihoaqua instance);
    partial void InsertNhacungcap(Nhacungcap instance);
    partial void UpdateNhacungcap(Nhacungcap instance);
    partial void DeleteNhacungcap(Nhacungcap instance);
    partial void InsertNhanvien(Nhanvien instance);
    partial void UpdateNhanvien(Nhanvien instance);
    partial void DeleteNhanvien(Nhanvien instance);
    partial void Inserthoaqua(hoaqua instance);
    partial void Updatehoaqua(hoaqua instance);
    partial void Deletehoaqua(hoaqua instance);
    partial void InsertChiTietHDN(ChiTietHDN instance);
    partial void UpdateChiTietHDN(ChiTietHDN instance);
    partial void DeleteChiTietHDN(ChiTietHDN instance);
    partial void InsertChitietHDB(ChitietHDB instance);
    partial void UpdateChitietHDB(ChitietHDB instance);
    partial void DeleteChitietHDB(ChitietHDB instance);
    #endregion
		
		public HoaquaDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLbanhoaqua3ConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public HoaquaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HoaquaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HoaquaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public HoaquaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Calamviec> Calamviecs
		{
			get
			{
				return this.GetTable<Calamviec>();
			}
		}
		
		public System.Data.Linq.Table<Chitietcalam> Chitietcalams
		{
			get
			{
				return this.GetTable<Chitietcalam>();
			}
		}
		
		public System.Data.Linq.Table<Hoadonban> Hoadonbans
		{
			get
			{
				return this.GetTable<Hoadonban>();
			}
		}
		
		public System.Data.Linq.Table<HoaDonNhap> HoaDonNhaps
		{
			get
			{
				return this.GetTable<HoaDonNhap>();
			}
		}
		
		public System.Data.Linq.Table<Khachhang> Khachhangs
		{
			get
			{
				return this.GetTable<Khachhang>();
			}
		}
		
		public System.Data.Linq.Table<Loaihoaqua> Loaihoaquas
		{
			get
			{
				return this.GetTable<Loaihoaqua>();
			}
		}
		
		public System.Data.Linq.Table<Nhacungcap> Nhacungcaps
		{
			get
			{
				return this.GetTable<Nhacungcap>();
			}
		}
		
		public System.Data.Linq.Table<Nhanvien> Nhanviens
		{
			get
			{
				return this.GetTable<Nhanvien>();
			}
		}
		
		public System.Data.Linq.Table<hoaqua> hoaquas
		{
			get
			{
				return this.GetTable<hoaqua>();
			}
		}
		
		public System.Data.Linq.Table<ChiTietHDN> ChiTietHDNs
		{
			get
			{
				return this.GetTable<ChiTietHDN>();
			}
		}
		
		public System.Data.Linq.Table<ChitietHDB> ChitietHDBs
		{
			get
			{
				return this.GetTable<ChitietHDB>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Calamviec")]
	public partial class Calamviec : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Maca;
		
		private System.Nullable<double> _Tienca;
		
		private System.Nullable<System.TimeSpan> _TGbatdau;
		
		private System.Nullable<System.TimeSpan> _TGKThuc;
		
		private EntityRef<Chitietcalam> _Chitietcalam;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMacaChanging(string value);
    partial void OnMacaChanged();
    partial void OnTiencaChanging(System.Nullable<double> value);
    partial void OnTiencaChanged();
    partial void OnTGbatdauChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTGbatdauChanged();
    partial void OnTGKThucChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTGKThucChanged();
    #endregion
		
		public Calamviec()
		{
			this._Chitietcalam = default(EntityRef<Chitietcalam>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maca", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Maca
		{
			get
			{
				return this._Maca;
			}
			set
			{
				if ((this._Maca != value))
				{
					this.OnMacaChanging(value);
					this.SendPropertyChanging();
					this._Maca = value;
					this.SendPropertyChanged("Maca");
					this.OnMacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tienca", DbType="Float")]
		public System.Nullable<double> Tienca
		{
			get
			{
				return this._Tienca;
			}
			set
			{
				if ((this._Tienca != value))
				{
					this.OnTiencaChanging(value);
					this.SendPropertyChanging();
					this._Tienca = value;
					this.SendPropertyChanged("Tienca");
					this.OnTiencaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGbatdau", DbType="Time")]
		public System.Nullable<System.TimeSpan> TGbatdau
		{
			get
			{
				return this._TGbatdau;
			}
			set
			{
				if ((this._TGbatdau != value))
				{
					this.OnTGbatdauChanging(value);
					this.SendPropertyChanging();
					this._TGbatdau = value;
					this.SendPropertyChanged("TGbatdau");
					this.OnTGbatdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGKThuc", DbType="Time")]
		public System.Nullable<System.TimeSpan> TGKThuc
		{
			get
			{
				return this._TGKThuc;
			}
			set
			{
				if ((this._TGKThuc != value))
				{
					this.OnTGKThucChanging(value);
					this.SendPropertyChanging();
					this._TGKThuc = value;
					this.SendPropertyChanged("TGKThuc");
					this.OnTGKThucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calamviec_Chitietcalam", Storage="_Chitietcalam", ThisKey="Maca", OtherKey="Maca", IsUnique=true, IsForeignKey=false)]
		public Chitietcalam Chitietcalam
		{
			get
			{
				return this._Chitietcalam.Entity;
			}
			set
			{
				Chitietcalam previousValue = this._Chitietcalam.Entity;
				if (((previousValue != value) 
							|| (this._Chitietcalam.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Chitietcalam.Entity = null;
						previousValue.Calamviec = null;
					}
					this._Chitietcalam.Entity = value;
					if ((value != null))
					{
						value.Calamviec = this;
					}
					this.SendPropertyChanged("Chitietcalam");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chitietcalam")]
	public partial class Chitietcalam : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNV;
		
		private string _Maca;
		
		private EntityRef<Calamviec> _Calamviec;
		
		private EntityRef<Nhanvien> _Nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMacaChanging(string value);
    partial void OnMacaChanged();
    #endregion
		
		public Chitietcalam()
		{
			this._Calamviec = default(EntityRef<Calamviec>);
			this._Nhanvien = default(EntityRef<Nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._Nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maca", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Maca
		{
			get
			{
				return this._Maca;
			}
			set
			{
				if ((this._Maca != value))
				{
					if (this._Calamviec.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMacaChanging(value);
					this.SendPropertyChanging();
					this._Maca = value;
					this.SendPropertyChanged("Maca");
					this.OnMacaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Calamviec_Chitietcalam", Storage="_Calamviec", ThisKey="Maca", OtherKey="Maca", IsForeignKey=true)]
		public Calamviec Calamviec
		{
			get
			{
				return this._Calamviec.Entity;
			}
			set
			{
				Calamviec previousValue = this._Calamviec.Entity;
				if (((previousValue != value) 
							|| (this._Calamviec.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Calamviec.Entity = null;
						previousValue.Chitietcalam = null;
					}
					this._Calamviec.Entity = value;
					if ((value != null))
					{
						value.Chitietcalam = this;
						this._Maca = value.Maca;
					}
					else
					{
						this._Maca = default(string);
					}
					this.SendPropertyChanged("Calamviec");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanvien_Chitietcalam", Storage="_Nhanvien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public Nhanvien Nhanvien
		{
			get
			{
				return this._Nhanvien.Entity;
			}
			set
			{
				Nhanvien previousValue = this._Nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._Nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhanvien.Entity = null;
						previousValue.Chitietcalams.Remove(this);
					}
					this._Nhanvien.Entity = value;
					if ((value != null))
					{
						value.Chitietcalams.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("Nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Hoadonban")]
	public partial class Hoadonban : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoHDB;
		
		private System.Nullable<System.DateTime> _Ngayban;
		
		private string _MaNV;
		
		private string _MaKH;
		
		private EntitySet<ChitietHDB> _ChitietHDBs;
		
		private EntityRef<Khachhang> _Khachhang;
		
		private EntityRef<Nhanvien> _Nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHDBChanging(string value);
    partial void OnSoHDBChanged();
    partial void OnNgaybanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaybanChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    #endregion
		
		public Hoadonban()
		{
			this._ChitietHDBs = new EntitySet<ChitietHDB>(new Action<ChitietHDB>(this.attach_ChitietHDBs), new Action<ChitietHDB>(this.detach_ChitietHDBs));
			this._Khachhang = default(EntityRef<Khachhang>);
			this._Nhanvien = default(EntityRef<Nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHDB", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoHDB
		{
			get
			{
				return this._SoHDB;
			}
			set
			{
				if ((this._SoHDB != value))
				{
					this.OnSoHDBChanging(value);
					this.SendPropertyChanging();
					this._SoHDB = value;
					this.SendPropertyChanged("SoHDB");
					this.OnSoHDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayban", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngayban
		{
			get
			{
				return this._Ngayban;
			}
			set
			{
				if ((this._Ngayban != value))
				{
					this.OnNgaybanChanging(value);
					this.SendPropertyChanging();
					this._Ngayban = value;
					this.SendPropertyChanged("Ngayban");
					this.OnNgaybanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(100)")]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._Nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					if (this._Khachhang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoadonban_ChitietHDB", Storage="_ChitietHDBs", ThisKey="SoHDB", OtherKey="SoHDB")]
		public EntitySet<ChitietHDB> ChitietHDBs
		{
			get
			{
				return this._ChitietHDBs;
			}
			set
			{
				this._ChitietHDBs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khachhang_Hoadonban", Storage="_Khachhang", ThisKey="MaKH", OtherKey="MaKH", IsForeignKey=true)]
		public Khachhang Khachhang
		{
			get
			{
				return this._Khachhang.Entity;
			}
			set
			{
				Khachhang previousValue = this._Khachhang.Entity;
				if (((previousValue != value) 
							|| (this._Khachhang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Khachhang.Entity = null;
						previousValue.Hoadonbans.Remove(this);
					}
					this._Khachhang.Entity = value;
					if ((value != null))
					{
						value.Hoadonbans.Add(this);
						this._MaKH = value.MaKH;
					}
					else
					{
						this._MaKH = default(string);
					}
					this.SendPropertyChanged("Khachhang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanvien_Hoadonban", Storage="_Nhanvien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public Nhanvien Nhanvien
		{
			get
			{
				return this._Nhanvien.Entity;
			}
			set
			{
				Nhanvien previousValue = this._Nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._Nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhanvien.Entity = null;
						previousValue.Hoadonbans.Remove(this);
					}
					this._Nhanvien.Entity = value;
					if ((value != null))
					{
						value.Hoadonbans.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("Nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChitietHDBs(ChitietHDB entity)
		{
			this.SendPropertyChanging();
			entity.Hoadonban = this;
		}
		
		private void detach_ChitietHDBs(ChitietHDB entity)
		{
			this.SendPropertyChanging();
			entity.Hoadonban = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HoaDonNhap")]
	public partial class HoaDonNhap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _SoHDN;
		
		private System.Nullable<System.DateTime> _NgayNhap;
		
		private string _MaNCC;
		
		private string _MaNV;
		
		private EntitySet<ChiTietHDN> _ChiTietHDNs;
		
		private EntityRef<Nhacungcap> _Nhacungcap;
		
		private EntityRef<Nhanvien> _Nhanvien;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSoHDNChanging(string value);
    partial void OnSoHDNChanged();
    partial void OnNgayNhapChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayNhapChanged();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    #endregion
		
		public HoaDonNhap()
		{
			this._ChiTietHDNs = new EntitySet<ChiTietHDN>(new Action<ChiTietHDN>(this.attach_ChiTietHDNs), new Action<ChiTietHDN>(this.detach_ChiTietHDNs));
			this._Nhacungcap = default(EntityRef<Nhacungcap>);
			this._Nhanvien = default(EntityRef<Nhanvien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHDN", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SoHDN
		{
			get
			{
				return this._SoHDN;
			}
			set
			{
				if ((this._SoHDN != value))
				{
					this.OnSoHDNChanging(value);
					this.SendPropertyChanging();
					this._SoHDN = value;
					this.SendPropertyChanged("SoHDN");
					this.OnSoHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayNhap", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayNhap
		{
			get
			{
				return this._NgayNhap;
			}
			set
			{
				if ((this._NgayNhap != value))
				{
					this.OnNgayNhapChanging(value);
					this.SendPropertyChanging();
					this._NgayNhap = value;
					this.SendPropertyChanged("NgayNhap");
					this.OnNgayNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					if (this._Nhacungcap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					if (this._Nhanvien.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonNhap_ChiTietHDN", Storage="_ChiTietHDNs", ThisKey="SoHDN", OtherKey="SoHDN")]
		public EntitySet<ChiTietHDN> ChiTietHDNs
		{
			get
			{
				return this._ChiTietHDNs;
			}
			set
			{
				this._ChiTietHDNs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhacungcap_HoaDonNhap", Storage="_Nhacungcap", ThisKey="MaNCC", OtherKey="MaNCC", IsForeignKey=true)]
		public Nhacungcap Nhacungcap
		{
			get
			{
				return this._Nhacungcap.Entity;
			}
			set
			{
				Nhacungcap previousValue = this._Nhacungcap.Entity;
				if (((previousValue != value) 
							|| (this._Nhacungcap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhacungcap.Entity = null;
						previousValue.HoaDonNhaps.Remove(this);
					}
					this._Nhacungcap.Entity = value;
					if ((value != null))
					{
						value.HoaDonNhaps.Add(this);
						this._MaNCC = value.MaNCC;
					}
					else
					{
						this._MaNCC = default(string);
					}
					this.SendPropertyChanged("Nhacungcap");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanvien_HoaDonNhap", Storage="_Nhanvien", ThisKey="MaNV", OtherKey="MaNV", IsForeignKey=true)]
		public Nhanvien Nhanvien
		{
			get
			{
				return this._Nhanvien.Entity;
			}
			set
			{
				Nhanvien previousValue = this._Nhanvien.Entity;
				if (((previousValue != value) 
							|| (this._Nhanvien.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Nhanvien.Entity = null;
						previousValue.HoaDonNhaps.Remove(this);
					}
					this._Nhanvien.Entity = value;
					if ((value != null))
					{
						value.HoaDonNhaps.Add(this);
						this._MaNV = value.MaNV;
					}
					else
					{
						this._MaNV = default(string);
					}
					this.SendPropertyChanged("Nhanvien");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_ChiTietHDNs(ChiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonNhap = this;
		}
		
		private void detach_ChiTietHDNs(ChiTietHDN entity)
		{
			this.SendPropertyChanging();
			entity.HoaDonNhap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Khachhang")]
	public partial class Khachhang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaKH;
		
		private string _TenKH;
		
		private string _Diachi;
		
		private int _SDT;
		
		private EntitySet<Hoadonban> _Hoadonbans;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaKHChanging(string value);
    partial void OnMaKHChanged();
    partial void OnTenKHChanging(string value);
    partial void OnTenKHChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnSDTChanging(int value);
    partial void OnSDTChanged();
    #endregion
		
		public Khachhang()
		{
			this._Hoadonbans = new EntitySet<Hoadonban>(new Action<Hoadonban>(this.attach_Hoadonbans), new Action<Hoadonban>(this.detach_Hoadonbans));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaKH", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaKH
		{
			get
			{
				return this._MaKH;
			}
			set
			{
				if ((this._MaKH != value))
				{
					this.OnMaKHChanging(value);
					this.SendPropertyChanging();
					this._MaKH = value;
					this.SendPropertyChanged("MaKH");
					this.OnMaKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenKH", DbType="NVarChar(250)")]
		public string TenKH
		{
			get
			{
				return this._TenKH;
			}
			set
			{
				if ((this._TenKH != value))
				{
					this.OnTenKHChanging(value);
					this.SendPropertyChanging();
					this._TenKH = value;
					this.SendPropertyChanged("TenKH");
					this.OnTenKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(250)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int NOT NULL")]
		public int SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Khachhang_Hoadonban", Storage="_Hoadonbans", ThisKey="MaKH", OtherKey="MaKH")]
		public EntitySet<Hoadonban> Hoadonbans
		{
			get
			{
				return this._Hoadonbans;
			}
			set
			{
				this._Hoadonbans.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Hoadonbans(Hoadonban entity)
		{
			this.SendPropertyChanging();
			entity.Khachhang = this;
		}
		
		private void detach_Hoadonbans(Hoadonban entity)
		{
			this.SendPropertyChanging();
			entity.Khachhang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Loaihoaqua")]
	public partial class Loaihoaqua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Maloai;
		
		private string _Tenloai;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaloaiChanging(string value);
    partial void OnMaloaiChanged();
    partial void OnTenloaiChanging(string value);
    partial void OnTenloaiChanged();
    #endregion
		
		public Loaihoaqua()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloai", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Maloai
		{
			get
			{
				return this._Maloai;
			}
			set
			{
				if ((this._Maloai != value))
				{
					this.OnMaloaiChanging(value);
					this.SendPropertyChanging();
					this._Maloai = value;
					this.SendPropertyChanged("Maloai");
					this.OnMaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenloai", DbType="NVarChar(250)")]
		public string Tenloai
		{
			get
			{
				return this._Tenloai;
			}
			set
			{
				if ((this._Tenloai != value))
				{
					this.OnTenloaiChanging(value);
					this.SendPropertyChanging();
					this._Tenloai = value;
					this.SendPropertyChanged("Tenloai");
					this.OnTenloaiChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhacungcap")]
	public partial class Nhacungcap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaNCC;
		
		private string _TenNCC;
		
		private EntitySet<HoaDonNhap> _HoaDonNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaNCCChanging(string value);
    partial void OnMaNCCChanged();
    partial void OnTenNCCChanging(string value);
    partial void OnTenNCCChanged();
    #endregion
		
		public Nhacungcap()
		{
			this._HoaDonNhaps = new EntitySet<HoaDonNhap>(new Action<HoaDonNhap>(this.attach_HoaDonNhaps), new Action<HoaDonNhap>(this.detach_HoaDonNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNCC", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNCC
		{
			get
			{
				return this._MaNCC;
			}
			set
			{
				if ((this._MaNCC != value))
				{
					this.OnMaNCCChanging(value);
					this.SendPropertyChanging();
					this._MaNCC = value;
					this.SendPropertyChanged("MaNCC");
					this.OnMaNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNCC", DbType="NVarChar(250)")]
		public string TenNCC
		{
			get
			{
				return this._TenNCC;
			}
			set
			{
				if ((this._TenNCC != value))
				{
					this.OnTenNCCChanging(value);
					this.SendPropertyChanging();
					this._TenNCC = value;
					this.SendPropertyChanged("TenNCC");
					this.OnTenNCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhacungcap_HoaDonNhap", Storage="_HoaDonNhaps", ThisKey="MaNCC", OtherKey="MaNCC")]
		public EntitySet<HoaDonNhap> HoaDonNhaps
		{
			get
			{
				return this._HoaDonNhaps;
			}
			set
			{
				this._HoaDonNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HoaDonNhaps(HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.Nhacungcap = this;
		}
		
		private void detach_HoaDonNhaps(HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.Nhacungcap = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nhanvien")]
	public partial class Nhanvien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TenNV;
		
		private string _MaNV;
		
		private string _GT;
		
		private System.Nullable<int> _SDT;
		
		private System.Nullable<System.DateTime> _Ngaysinh;
		
		private string _Diachi;
		
		private EntitySet<Chitietcalam> _Chitietcalams;
		
		private EntitySet<Hoadonban> _Hoadonbans;
		
		private EntitySet<HoaDonNhap> _HoaDonNhaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenNVChanging(string value);
    partial void OnTenNVChanged();
    partial void OnMaNVChanging(string value);
    partial void OnMaNVChanged();
    partial void OnGTChanging(string value);
    partial void OnGTChanged();
    partial void OnSDTChanging(System.Nullable<int> value);
    partial void OnSDTChanged();
    partial void OnNgaysinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaysinhChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    #endregion
		
		public Nhanvien()
		{
			this._Chitietcalams = new EntitySet<Chitietcalam>(new Action<Chitietcalam>(this.attach_Chitietcalams), new Action<Chitietcalam>(this.detach_Chitietcalams));
			this._Hoadonbans = new EntitySet<Hoadonban>(new Action<Hoadonban>(this.attach_Hoadonbans), new Action<Hoadonban>(this.detach_Hoadonbans));
			this._HoaDonNhaps = new EntitySet<HoaDonNhap>(new Action<HoaDonNhap>(this.attach_HoaDonNhaps), new Action<HoaDonNhap>(this.detach_HoaDonNhaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenNV", DbType="NVarChar(250)")]
		public string TenNV
		{
			get
			{
				return this._TenNV;
			}
			set
			{
				if ((this._TenNV != value))
				{
					this.OnTenNVChanging(value);
					this.SendPropertyChanging();
					this._TenNV = value;
					this.SendPropertyChanged("TenNV");
					this.OnTenNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaNV", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaNV
		{
			get
			{
				return this._MaNV;
			}
			set
			{
				if ((this._MaNV != value))
				{
					this.OnMaNVChanging(value);
					this.SendPropertyChanging();
					this._MaNV = value;
					this.SendPropertyChanged("MaNV");
					this.OnMaNVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GT", DbType="NVarChar(250)")]
		public string GT
		{
			get
			{
				return this._GT;
			}
			set
			{
				if ((this._GT != value))
				{
					this.OnGTChanging(value);
					this.SendPropertyChanging();
					this._GT = value;
					this.SendPropertyChanged("GT");
					this.OnGTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SDT", DbType="Int")]
		public System.Nullable<int> SDT
		{
			get
			{
				return this._SDT;
			}
			set
			{
				if ((this._SDT != value))
				{
					this.OnSDTChanging(value);
					this.SendPropertyChanging();
					this._SDT = value;
					this.SendPropertyChanged("SDT");
					this.OnSDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaysinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> Ngaysinh
		{
			get
			{
				return this._Ngaysinh;
			}
			set
			{
				if ((this._Ngaysinh != value))
				{
					this.OnNgaysinhChanging(value);
					this.SendPropertyChanging();
					this._Ngaysinh = value;
					this.SendPropertyChanged("Ngaysinh");
					this.OnNgaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="NVarChar(250)")]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanvien_Chitietcalam", Storage="_Chitietcalams", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<Chitietcalam> Chitietcalams
		{
			get
			{
				return this._Chitietcalams;
			}
			set
			{
				this._Chitietcalams.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanvien_Hoadonban", Storage="_Hoadonbans", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<Hoadonban> Hoadonbans
		{
			get
			{
				return this._Hoadonbans;
			}
			set
			{
				this._Hoadonbans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Nhanvien_HoaDonNhap", Storage="_HoaDonNhaps", ThisKey="MaNV", OtherKey="MaNV")]
		public EntitySet<HoaDonNhap> HoaDonNhaps
		{
			get
			{
				return this._HoaDonNhaps;
			}
			set
			{
				this._HoaDonNhaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Chitietcalams(Chitietcalam entity)
		{
			this.SendPropertyChanging();
			entity.Nhanvien = this;
		}
		
		private void detach_Chitietcalams(Chitietcalam entity)
		{
			this.SendPropertyChanging();
			entity.Nhanvien = null;
		}
		
		private void attach_Hoadonbans(Hoadonban entity)
		{
			this.SendPropertyChanging();
			entity.Nhanvien = this;
		}
		
		private void detach_Hoadonbans(Hoadonban entity)
		{
			this.SendPropertyChanging();
			entity.Nhanvien = null;
		}
		
		private void attach_HoaDonNhaps(HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.Nhanvien = this;
		}
		
		private void detach_HoaDonNhaps(HoaDonNhap entity)
		{
			this.SendPropertyChanging();
			entity.Nhanvien = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.hoaqua")]
	public partial class hoaqua : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Tenhoaqua;
		
		private string _mahoaqua;
		
		private System.Nullable<int> _dongiaban;
		
		private string _Anh;
		
		private System.Nullable<int> _Dongianhap;
		
		private string _Mota;
		
		private string _Maloai;
		
		private string _trongluong;
		
		private EntityRef<ChiTietHDN> _ChiTietHDN;
		
		private EntityRef<ChitietHDB> _ChitietHDB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTenhoaquaChanging(string value);
    partial void OnTenhoaquaChanged();
    partial void OnmahoaquaChanging(string value);
    partial void OnmahoaquaChanged();
    partial void OndongiabanChanging(System.Nullable<int> value);
    partial void OndongiabanChanged();
    partial void OnAnhChanging(string value);
    partial void OnAnhChanged();
    partial void OnDongianhapChanging(System.Nullable<int> value);
    partial void OnDongianhapChanged();
    partial void OnMotaChanging(string value);
    partial void OnMotaChanged();
    partial void OnMaloaiChanging(string value);
    partial void OnMaloaiChanged();
    partial void OntrongluongChanging(string value);
    partial void OntrongluongChanged();
    #endregion
		
		public hoaqua()
		{
			this._ChiTietHDN = default(EntityRef<ChiTietHDN>);
			this._ChitietHDB = default(EntityRef<ChitietHDB>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenhoaqua", DbType="NVarChar(250)")]
		public string Tenhoaqua
		{
			get
			{
				return this._Tenhoaqua;
			}
			set
			{
				if ((this._Tenhoaqua != value))
				{
					this.OnTenhoaquaChanging(value);
					this.SendPropertyChanging();
					this._Tenhoaqua = value;
					this.SendPropertyChanged("Tenhoaqua");
					this.OnTenhoaquaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahoaqua", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahoaqua
		{
			get
			{
				return this._mahoaqua;
			}
			set
			{
				if ((this._mahoaqua != value))
				{
					this.OnmahoaquaChanging(value);
					this.SendPropertyChanging();
					this._mahoaqua = value;
					this.SendPropertyChanged("mahoaqua");
					this.OnmahoaquaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dongiaban", DbType="Int")]
		public System.Nullable<int> dongiaban
		{
			get
			{
				return this._dongiaban;
			}
			set
			{
				if ((this._dongiaban != value))
				{
					this.OndongiabanChanging(value);
					this.SendPropertyChanging();
					this._dongiaban = value;
					this.SendPropertyChanged("dongiaban");
					this.OndongiabanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Anh", DbType="Char(100)")]
		public string Anh
		{
			get
			{
				return this._Anh;
			}
			set
			{
				if ((this._Anh != value))
				{
					this.OnAnhChanging(value);
					this.SendPropertyChanging();
					this._Anh = value;
					this.SendPropertyChanged("Anh");
					this.OnAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dongianhap", DbType="Int")]
		public System.Nullable<int> Dongianhap
		{
			get
			{
				return this._Dongianhap;
			}
			set
			{
				if ((this._Dongianhap != value))
				{
					this.OnDongianhapChanging(value);
					this.SendPropertyChanging();
					this._Dongianhap = value;
					this.SendPropertyChanged("Dongianhap");
					this.OnDongianhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mota", DbType="NVarChar(250)")]
		public string Mota
		{
			get
			{
				return this._Mota;
			}
			set
			{
				if ((this._Mota != value))
				{
					this.OnMotaChanging(value);
					this.SendPropertyChanging();
					this._Mota = value;
					this.SendPropertyChanged("Mota");
					this.OnMotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Maloai", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Maloai
		{
			get
			{
				return this._Maloai;
			}
			set
			{
				if ((this._Maloai != value))
				{
					this.OnMaloaiChanging(value);
					this.SendPropertyChanging();
					this._Maloai = value;
					this.SendPropertyChanged("Maloai");
					this.OnMaloaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_trongluong", DbType="VarChar(255)")]
		public string trongluong
		{
			get
			{
				return this._trongluong;
			}
			set
			{
				if ((this._trongluong != value))
				{
					this.OntrongluongChanging(value);
					this.SendPropertyChanging();
					this._trongluong = value;
					this.SendPropertyChanged("trongluong");
					this.OntrongluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoaqua_ChiTietHDN", Storage="_ChiTietHDN", ThisKey="mahoaqua", OtherKey="mahoaqua", IsUnique=true, IsForeignKey=false)]
		public ChiTietHDN ChiTietHDN
		{
			get
			{
				return this._ChiTietHDN.Entity;
			}
			set
			{
				ChiTietHDN previousValue = this._ChiTietHDN.Entity;
				if (((previousValue != value) 
							|| (this._ChiTietHDN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChiTietHDN.Entity = null;
						previousValue.hoaqua = null;
					}
					this._ChiTietHDN.Entity = value;
					if ((value != null))
					{
						value.hoaqua = this;
					}
					this.SendPropertyChanged("ChiTietHDN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoaqua_ChitietHDB", Storage="_ChitietHDB", ThisKey="mahoaqua", OtherKey="mahoaqua", IsUnique=true, IsForeignKey=false)]
		public ChitietHDB ChitietHDB
		{
			get
			{
				return this._ChitietHDB.Entity;
			}
			set
			{
				ChitietHDB previousValue = this._ChitietHDB.Entity;
				if (((previousValue != value) 
							|| (this._ChitietHDB.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChitietHDB.Entity = null;
						previousValue.hoaqua = null;
					}
					this._ChitietHDB.Entity = value;
					if ((value != null))
					{
						value.hoaqua = this;
					}
					this.SendPropertyChanged("ChitietHDB");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChiTietHDN")]
	public partial class ChiTietHDN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<int> _SLNhap;
		
		private string _mahoaqua;
		
		private string _SoHDN;
		
		private EntityRef<hoaqua> _hoaqua;
		
		private EntityRef<HoaDonNhap> _HoaDonNhap;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSLNhapChanging(System.Nullable<int> value);
    partial void OnSLNhapChanged();
    partial void OnmahoaquaChanging(string value);
    partial void OnmahoaquaChanged();
    partial void OnSoHDNChanging(string value);
    partial void OnSoHDNChanged();
    #endregion
		
		public ChiTietHDN()
		{
			this._hoaqua = default(EntityRef<hoaqua>);
			this._HoaDonNhap = default(EntityRef<HoaDonNhap>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLNhap", DbType="Int")]
		public System.Nullable<int> SLNhap
		{
			get
			{
				return this._SLNhap;
			}
			set
			{
				if ((this._SLNhap != value))
				{
					this.OnSLNhapChanging(value);
					this.SendPropertyChanging();
					this._SLNhap = value;
					this.SendPropertyChanged("SLNhap");
					this.OnSLNhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahoaqua", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahoaqua
		{
			get
			{
				return this._mahoaqua;
			}
			set
			{
				if ((this._mahoaqua != value))
				{
					if (this._hoaqua.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahoaquaChanging(value);
					this.SendPropertyChanging();
					this._mahoaqua = value;
					this.SendPropertyChanged("mahoaqua");
					this.OnmahoaquaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHDN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SoHDN
		{
			get
			{
				return this._SoHDN;
			}
			set
			{
				if ((this._SoHDN != value))
				{
					if (this._HoaDonNhap.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoHDNChanging(value);
					this.SendPropertyChanging();
					this._SoHDN = value;
					this.SendPropertyChanged("SoHDN");
					this.OnSoHDNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoaqua_ChiTietHDN", Storage="_hoaqua", ThisKey="mahoaqua", OtherKey="mahoaqua", IsForeignKey=true)]
		public hoaqua hoaqua
		{
			get
			{
				return this._hoaqua.Entity;
			}
			set
			{
				hoaqua previousValue = this._hoaqua.Entity;
				if (((previousValue != value) 
							|| (this._hoaqua.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoaqua.Entity = null;
						previousValue.ChiTietHDN = null;
					}
					this._hoaqua.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDN = this;
						this._mahoaqua = value.mahoaqua;
					}
					else
					{
						this._mahoaqua = default(string);
					}
					this.SendPropertyChanged("hoaqua");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HoaDonNhap_ChiTietHDN", Storage="_HoaDonNhap", ThisKey="SoHDN", OtherKey="SoHDN", IsForeignKey=true)]
		public HoaDonNhap HoaDonNhap
		{
			get
			{
				return this._HoaDonNhap.Entity;
			}
			set
			{
				HoaDonNhap previousValue = this._HoaDonNhap.Entity;
				if (((previousValue != value) 
							|| (this._HoaDonNhap.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HoaDonNhap.Entity = null;
						previousValue.ChiTietHDNs.Remove(this);
					}
					this._HoaDonNhap.Entity = value;
					if ((value != null))
					{
						value.ChiTietHDNs.Add(this);
						this._SoHDN = value.SoHDN;
					}
					else
					{
						this._SoHDN = default(string);
					}
					this.SendPropertyChanged("HoaDonNhap");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChitietHDB")]
	public partial class ChitietHDB : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Khuyenmai;
		
		private System.Nullable<int> _SLB;
		
		private string _mahoaqua;
		
		private string _SoHDB;
		
		private EntityRef<hoaqua> _hoaqua;
		
		private EntityRef<Hoadonban> _Hoadonban;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKhuyenmaiChanging(string value);
    partial void OnKhuyenmaiChanged();
    partial void OnSLBChanging(System.Nullable<int> value);
    partial void OnSLBChanged();
    partial void OnmahoaquaChanging(string value);
    partial void OnmahoaquaChanged();
    partial void OnSoHDBChanging(string value);
    partial void OnSoHDBChanged();
    #endregion
		
		public ChitietHDB()
		{
			this._hoaqua = default(EntityRef<hoaqua>);
			this._Hoadonban = default(EntityRef<Hoadonban>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Khuyenmai", DbType="NVarChar(100)")]
		public string Khuyenmai
		{
			get
			{
				return this._Khuyenmai;
			}
			set
			{
				if ((this._Khuyenmai != value))
				{
					this.OnKhuyenmaiChanging(value);
					this.SendPropertyChanging();
					this._Khuyenmai = value;
					this.SendPropertyChanged("Khuyenmai");
					this.OnKhuyenmaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SLB", DbType="Int")]
		public System.Nullable<int> SLB
		{
			get
			{
				return this._SLB;
			}
			set
			{
				if ((this._SLB != value))
				{
					this.OnSLBChanging(value);
					this.SendPropertyChanging();
					this._SLB = value;
					this.SendPropertyChanged("SLB");
					this.OnSLBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mahoaqua", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string mahoaqua
		{
			get
			{
				return this._mahoaqua;
			}
			set
			{
				if ((this._mahoaqua != value))
				{
					if (this._hoaqua.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmahoaquaChanging(value);
					this.SendPropertyChanging();
					this._mahoaqua = value;
					this.SendPropertyChanged("mahoaqua");
					this.OnmahoaquaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoHDB", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string SoHDB
		{
			get
			{
				return this._SoHDB;
			}
			set
			{
				if ((this._SoHDB != value))
				{
					if (this._Hoadonban.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSoHDBChanging(value);
					this.SendPropertyChanging();
					this._SoHDB = value;
					this.SendPropertyChanged("SoHDB");
					this.OnSoHDBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="hoaqua_ChitietHDB", Storage="_hoaqua", ThisKey="mahoaqua", OtherKey="mahoaqua", IsForeignKey=true)]
		public hoaqua hoaqua
		{
			get
			{
				return this._hoaqua.Entity;
			}
			set
			{
				hoaqua previousValue = this._hoaqua.Entity;
				if (((previousValue != value) 
							|| (this._hoaqua.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._hoaqua.Entity = null;
						previousValue.ChitietHDB = null;
					}
					this._hoaqua.Entity = value;
					if ((value != null))
					{
						value.ChitietHDB = this;
						this._mahoaqua = value.mahoaqua;
					}
					else
					{
						this._mahoaqua = default(string);
					}
					this.SendPropertyChanged("hoaqua");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Hoadonban_ChitietHDB", Storage="_Hoadonban", ThisKey="SoHDB", OtherKey="SoHDB", IsForeignKey=true)]
		public Hoadonban Hoadonban
		{
			get
			{
				return this._Hoadonban.Entity;
			}
			set
			{
				Hoadonban previousValue = this._Hoadonban.Entity;
				if (((previousValue != value) 
							|| (this._Hoadonban.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Hoadonban.Entity = null;
						previousValue.ChitietHDBs.Remove(this);
					}
					this._Hoadonban.Entity = value;
					if ((value != null))
					{
						value.ChitietHDBs.Add(this);
						this._SoHDB = value.SoHDB;
					}
					else
					{
						this._SoHDB = default(string);
					}
					this.SendPropertyChanged("Hoadonban");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
